version: 18
jobs:
- name: Push-to-github
  steps:
  - !PushRepository
    name: push
    remoteUrl: https://github.com/JonathanMbt/Phoenicis
    passwordSecret: Github-Mirror-Token
    withLfs: false
    force: true
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  - !TagCreateTrigger {}
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
- name: CICD
  steps:
  - !CheckoutStep
    name: Checkout
    cloneCredential: !DefaultCredential {}
    withLfs: false
    withSubmodules: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  - !CommandStep
    name: Lint
    runInContainer: true
    image: node:gallium-alpine3.16
    interpreter: !DefaultInterpreter
      commands:
      - npm ci
      - npm run lint
    useTTY: false
    condition: ALL_PREVIOUS_STEPS_WERE_SUCCESSFUL
  triggers:
  - !BranchUpdateTrigger {}
  jobDependencies:
  - jobName: Push-to-github
    requireSuccessful: true
    artifacts: '**'
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  cpuRequirement: 250
  memoryRequirement: 256
  timeout: 3600
