version: "3.6"

services:
  phoenicis-www:
    image: react-nginx # custom image
    container_name: phoenicis-www
    volumes:
      - ./build:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "127.0.0.1:5001:80"
    networks:
      - home
    restart: unless-stopped
    labels:
      traefik.enable: true
      
      traefik.http.middlewares.force-secure.redirectscheme.scheme: https
      traefik.http.middlewares.force-secure.redirectscheme.permanent: true
      
      traefik.http.routers.phoenicis.entrypoints: websecure
      traefik.http.routers.phoenicis.rule: Host(`phoenicis-game.com`)
      traefik.http.routers.phoenicis.tls: true
      traefik.http.routers.phoenicis.tls.certresolver: production
      traefik.http.routers.phoenicis.middlewares: myfail2ban@file
      
      traefik.http.routers.phoenicis-insecure.entrypoints: web
      traefik.http.routers.phoenicis-insecure.rule: Host(`phoenicis-game.com`)
      traefik.http.routers.phoenicis-insecure.middlewares: force-secure, myfail2ban@file

networks:
  home:
    external: true
