version: "3.6"

services:
  phoenicis-www:
    build:
      context: .
      dockerfile: ./build/www/Dockerfile
    container_name: phoenicis-www
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "5001:80"
    networks:
      - home
    restart: unless-stopped
    labels:
      traefik.enable: true

      traefik.http.routers.phoenicis.entrypoints: websecure
      traefik.http.routers.phoenicis.rule: Host(`phoenicis-game.com`) || Host(`www.phoenicis-game.com`)
      traefik.http.routers.phoenicis.tls: true
      traefik.http.routers.phoenicis.tls.certresolver: production
      traefik.http.routers.phoenicis.middlewares: myfail2ban@file

      traefik.http.routers.phoenicis-insecure.entrypoints: web
      traefik.http.routers.phoenicis-insecure.rule: Host(`phoenicis-game.com`) || Host(`www.phoenicis-game.com`)
      traefik.http.routers.phoenicis-insecure.middlewares: force-secure@file

  phoenicis-api:
    build:
      context: .
      dockerfile: ./build/api/Dockerfile
    container_name: phoenicis-api
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "6000-6002:3333"
    networks:
      - home
      - db
    restart: unless-stopped
    labels:
        traefik.enable: true

        traefik.docker.network: home

        traefik.http.routers.phoenicis.entrypoints: websecure
        traefik.http.routers.phoenicis.rule: Host(`phoenicis-game.com`) && PathPrefix(`/api`) || Host(`www.phoenicis-game.com`) && PathPrefix(`/api`)
        traefik.http.routers.phoenicis.tls: true
        traefik.http.routers.phoenicis.tls.certresolver: production

        traefik.http.routers.phoenicis-insecure.entrypoints: web
        traefik.http.routers.phoenicis-insecure.rule: Host(`phoenicis-game.com`) && PathPrefix(`/api`) || Host(`www.phoenicis-game.com`) && PathPrefix(`/api`)
        traefik.http.routers.phoenicis-insecure.middlewares: force-secure@file
    environment:
      - REDIS_HOST=fs_redis
      - MONGO_HOST=fs_mongo
    deploy:
      mode: replicated
      replicas: 2
      endpoint_mode: vip
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

networks:
  home:
    external: true
  db:
    external: true
