name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
            ~/.npm
          key: Phoenicis-build-${{ github.ref_name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            Phoenicis-build-${{ github.ref_name }}

      # - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
      #  name: Install dependencies
      #  run: npm ci
        
      # - name: Lint
      #  run: npm run lint

      - name: Build
        run: npm run build --if-present
  
      - name: Deploy to Docker Host
        if: ${{ github.ref_name	== 'main' }}
        uses: JonathanMbt/docker-deployment-action@v5.5
        with:
          remote_docker_host: jonathan@${{ secrets.SSH_HOST }}
          remote_docker_port: 8822
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose
          copy_stack_file: true
          deploy_path: ~/phoenicis
          build_path: ./www/dist/*
          stack_file_name: docker-compose.yml
          args: up -d
          pull_images_first: false
