name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        working-directory: ./www
        run: npm ci
        
      - name: Lint
        working-directory: ./www
        run: npm run lint

      - name: Build
        working-directory: ./www
        run: npm run build --if-present
  
      - name: Deploy to Docker Host
        uses: wshihadeh/docker-deployment-action@v2
        with:
          remote_docker_host: jonathan@calen.unknownhost.ml
          remote_docker_port: 8822
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose
          args: up -d
          docker_prune: "true"
          pull_images_first: "true"
