name: CI

on: 
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: |
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: Install dependencies
        working-directory: ./www
        run: npm ci
        
      - name: Lint
        working-directory: ./www
        run: npm run lint

      - name: Build
        working-directory: ./www
        run: npm run build --if-present
  
      - name: Deploy to Docker Host
        if: ${{ github.ref_name	== 'main' }}
        uses: JonathanMbt/docker-deployment-action@v5.4
        with:
          remote_docker_host: jonathan@calen.unknownhost.ml
          remote_proxy_host: 1m897_mbtjonathan@1m897.ftp.infomaniak.com
          remote_docker_port: 8822
          ssh_public_proxy_key: ${{ secrets.SSH_PUBLIC_PROXY_KEY }}
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_public_key: ${{ secrets.SSH_PUBLIC_KEY }}
          deployment_mode: docker-compose
          copy_stack_file: true
          deploy_path: ~/docker/phoenicis
          build_path: ./www/dist/*
          stack_file_name: docker-compose.yml
          args: up -d
          pull_images_first: true
